export const INTERNSHIP_TRACKS = [
  'Computer Science',
  'Software Engineering',
  'Data Science',
  'Web Development',
  'Mobile Development',
  'Artificial Intelligence',
  'Machine Learning',
  'Deep Learning',
  'Cybersecurity',
  'Cloud Computing',
  'DevOps',
  'Database Administration',
  'Network Engineering',
  'UI/UX Design',
  'Game Development',
  'Embedded Systems',
  'Information Technology',
  'Business Intelligence',
  'Blockchain',
  'IoT',
  'Computer Vision',
  'Natural Language Processing',
  'Robotics',
  'Systems Administration',
  'Quality Assurance',
  'Technical Writing',
];
